application: egg-crackin
version: 1
runtime: go
api_version: go1

handlers:
        - url: /
          static_files: dist/index.html
          upload: dist/(.*\.html)
        - url: /(.*\.js)
          static_files: dist/\1
          upload: dist/(.*\.js)

        - url: /vendor
          static_dir: dist/vendor
        - url: /app
          static_dir: dist/app
        - url: /.*
          script: _go_app

skip_files:
        - ^node_modules$
        - node_modules
        - ^src$
        - ^public
        - ^tmp$
        - ^typings$


